name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
    - name: Install dependencies
      run: go mod download
    - name: Build
      run: go build -v ./...
    - name: Run Tests
      run: go test -v ./...
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        files: coverage/coverage.out
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
        verbose: true
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
